### ISSUE TITLE
Explain what KUSBA is

### ISSUE THREAD

**Issue by jueank** [xbst/KUSBA-PRO#1]
I just navigated to this Github project. There is not a single sentence explaining what this is about to begin with. I have no idea what KUSBA is. Or what's the difference between the 2 versions shown in the table.

**Comment by xbst** [comment]
KUSBA stands for Klipper USB Accelerometer. It's an USB accelerometer for measuring resonances for Klipper's input shaping. In terms of the components on the PCB, it's an accelerometer and an MCU running Klipper firmware (or Rampon on KUSBA v2), connected to the computer running Klipper with an USB cable.
KUSBA v2 has an ADXL345 accelerometer and a RP2040 MCU, running Klipper or Rampon firmware. It's primarily designed for mounting somewhere on a 3D printer's toolhead. It can be nozzle-mounted too but it's difficult.
KUSBA PRO addresses this by having an integrated, MJF-printed, clamp-style nozzle mount. It also uses different (arguably slightly superior) components for MCU and acclerometer. (RP2040 and ADXL345 vs STM32F042 and LIS2DW)

**Comment by jueank** [comment]
Thank you for the explanation. I would recommend to poste this into the README.md
