### ISSUE TITLE
Unable to compile klipper due to lack of space in rom

### ISSUE THREAD

**Issue by staticanime** [xbst/KUSBA-PRO#2]
Getting the following when trying to compile klipper for the KUSBA PRO

make KCONFIG_CONFIG=klipper-xbst-kusba.config
```
Version: v0.12.0-0-g0d67d9c4
  Preprocessing out/src/generic/armcm_link.ld
  Linking out/klipper.elf
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: out/klipper.elf section `.text' will not fit in region `rom'
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: region `rom' overflowed by 532 bytes
collect2: error: ld returned 1 exit status
make: *** [Makefile:72: out/klipper.elf] Error 1
```

Contents of the **make menuconfig KCONFIG_CONFIG=klipper-xbst-kusba.config** file:
![image](https://github.com/xbst/KUSBA-PRO/assets/394875/f31f0902-aaec-4529-87f8-9b35d4c2ad91)
![image](https://github.com/xbst/KUSBA-PRO/assets/394875/9dd6d99f-95df-445a-97b3-930fb4ec8cde)

**Comment by xbst** [comment]
You can try disabling more. "Support software based I2C "bit-banging"" should be safe to disable.

**Comment by staticanime** [comment]
Ok, cool, will try that now, wasn't sure what else would be safe to disable! Report back in a few minutes!

EDIT: Yup, thats done the trick, compiled successfully now!
