### ISSUE TITLE
Firmware update | usb pins

### ISSUE THREAD

**Issue by Valevach** [xbst/KUSBA-PRO#3]
Hi!
Im trying to update firmware on STM32F042 using instruction at
https://github.com/xbst/KUSBA-PRO/blob/master/Docs/Firmware.md

After successful flashing process via DFU, I didn`t receive any device at lsusb. 
Even after pull-out the wire ang plug again - no new messages at dmesg

I see there is menuconfig configuration line like:
Communication interface (USB (on PA9/PA10))  --->

But I have only option USB (on PA11/PA12)
Pins are mismatched? Also i have option Serial (on USART1 PA10/PA9)

How to build it?

**Comment by xbst** [comment]
Make sure to enable low level options. The correct USB pins will be added to the list.
________________________________
From: Oleksii Valevach ***@***.***>
Sent: Saturday, December 16, 2023 10:08:50 AM
To: xbst/KUSBA-PRO ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [xbst/KUSBA-PRO] Firmware update | usb pins (Issue #3)


Hi!
Im trying to update firmware on STM32F042 using instruction at
https://github.com/xbst/KUSBA-PRO/blob/master/Docs/Firmware.md

After successful flashing process via DFU, I didn`t receive any device at lsusb.
Even after pull-out the wire ang plug again - no new messages at dmesg

I see there is menuconfig configuration line like:
Communication interface (USB (on PA9/PA10)) --->

But I have only option USB (on PA11/PA12)
Pins are mismatched? Also i have option Serial (on USART1 PA10/PA9)

How to build it?

**Comment by Valevach** [comment]
Oh thank you!

Also this setting required:
    Clock Reference (Internal clock)  --->

Now it looks work.
