### ISSUE TITLE
Order PCB issue

### ISSUE THREAD

**Issue by HangryPanda** [xbst/KUSBA-PRO#6]
Hi, I attempted to place an order through PCBWay and the engineer replied with the following: 

 for black soldermask, we need the IC spacing to be 0.22 mm at least, otherwise the soldermask bridge can not be produced.  Do you need soldermsk bridge?
If so, pls enlarge the IC spacing to be 0.22mm at least, then send us the new file back.
If not, we will make the whole area exposed with soldermask opening where the IC spacing is not large enough.  In this case there is no soldermask ink between IC pads, and it's not good for soldering. Is it ok for you?

I have no experience whatsoever designing/editing PCBs. What should I do? 

Thanks. I would have purchased from you, but you're sold out. 
![W643937AS1H2](https://github.com/xbst/KUSBA-PRO/assets/8636467/f0c03f9d-1fa7-402b-8ba8-5896e57172a5)

**Comment by xbst** [comment]
This PCB is a tricky one for PCB manufacturers to make. I wanted to make the PCB as small as possible, so I used small chips and 0201 passives. This requires better tolerances on the PCB.

There's no way to enlarge IC pin spacing, that's the spacing of the pins of that chip. You can't just make that larger without changing the chip. Removing the soldermask _might_ work, but it's risky. Soldermask between those pads helps prevent bridged pads (shorts).

They may have a more expensive service with better tolerances. Or they might be able to make them with a different color soldermask. If not, I wouldn't order it. Other PCB manufacturers might be able to do it.

XR Bunker is sold out but I have them in stock (except Revo size): https://store.isiks.tech/products/kusba-pro-1

**Comment by HangryPanda** [comment]
Thanks for replying so quickly! I just placed my order on your website. I wonder if the color of the soldermask affects the tolerances. I chose black but perhaps the default color might work? I'll ask them if only to satisfy my own curiosity. Once I get a reply, I'll add it here and close out the issue.

**Comment by HangryPanda** [comment]
Here's the response from PCBWay  

`"1) There's no influence on tolerance if we change the solder mask color. It's suggested changing to green as we need min 0.19mm IC spacing for this color. Is it OK for you?"`

I'm going to interpret this as yes it does influence the tolerances. So choose green if there are tight tolerances without needing to pay extra for a high accuracy build process* 

*to a degree.
